#!/bin/bash
HTTP_USER=www-data
HTTP_GROUP=www-data

###########
#
#  Rechte
#
###########


chmod 775 /etc/init.d/nagios* /etc/init.d/ndo /etc/init.d/snmptrapd /etc/init.d/npcd
chmod o+r /dev/random /dev/urandom
chmod 664 /opt/openitc/* -R
chmod -R 775 /opt/openitc/nagios/libexec
chmod 775 /opt/openitc/
chmod 775 /opt
find /opt/openitc -type d -print0 |/usr/bin/xargs -0 /bin/chmod 775
chmod 775 /opt/openitc/nagios/bin/* -R
chmod 775 /opt/openitc/nagios/sbin/* -R
chmod g+w /opt/openitc/nagios/3rd/* -R
chmod 660 /opt/openitc/.htpasswd
chmod 775 /usr/bin/itc-*
chmod 600 /var/spool/cron/crontabs/*

###########
#
#  Eigner
#
###########

chown root:root /etc/init.d/nagios* /etc/init.d/ndo /etc/init.d/snmptrapd /etc/init.d/npcd
chown nagios:$HTTP_GROUP /opt/openitc/
chown nagios:$HTTP_GROUP /opt/openitc/* -R
chown nagios:$HTTP_GROUP /opt/openitc/.htpasswd
chown nagios:$HTTP_GROUP /opt/openitc/nagios/3rd/
chown nagios:$HTTP_GROUP /opt/openitc/nagios/3rd/* -R
chown nagios:$HTTP_GROUP /opt/openitc/nagios/archives/
chown nagios:$HTTP_GROUP /opt/openitc/nagios/archives/* -R
chown nagios:$HTTP_GROUP /opt/openitc/nagios/etc/
chown nagios:$HTTP_GROUP /opt/openitc/nagios/etc/* -R
chown nagios:$HTTP_GROUP /opt/openitc/nagios/sbin/
chown nagios:$HTTP_GROUP /opt/openitc/nagios/sbin/* -R
chown $HTTP_USER:$HTTP_GROUP /opt/openitc/nagios/share/
chown $HTTP_USER:$HTTP_GROUP /opt/openitc/nagios/share/* -R
chown nagios:$HTTP_GROUP /opt/openitc/nagios/var/
chown nagios:$HTTP_GROUP /opt/openitc/nagios/var/* -R
chown nagios:$HTTP_GROUP /opt/openitc/nagios/share/pnp/
chown nagios:$HTTP_GROUP /opt/openitc/nagios/share/pnp/* -R
chown nagios:$HTTP_GROUP /opt/openitc/nagios/share/perfdata/
chown nagios:$HTTP_GROUP /opt/openitc/nagios/share/perfdata/* -R
chown $HTTP_USER:crontab /var/spool/cron/crontabs/www-data
chown nagios:crontab /var/spool/cron/crontabs/nagios

###########
#
#  sonder Dateien
#
###########

chown root:$HTTP_GROUP /opt/openitc/nagios/libexec/check_icmp
chmod u+s /opt/openitc/nagios/libexec/check_icmp
chown root:$HTTP_GROUP /opt/openitc/nagios/libexec/check_dhcp
chmod u+s /opt/openitc/nagios/libexec/check_dhcp
